---
title: "progress-report-Final"
author: "Team 4"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
```

#### Cleaning and getting the data to match formats

Grab data from website (Munging)

```{r}
  url <- "https://www.baseball-reference.com/awards/hof_2024.shtml"
  html <- read_html(url)
  hof_table <- html %>%
  
    html_table(fill = TRUE) %>%
    .[[1]] 
  
  
 
  colnames(hof_table) <- hof_table[1, ]
  
  hof_table <- hof_table %>%
    select("Name","YoB","Votes","%vote","HOFm","HOFs","Yrs","WAR","WAR7","JAWS","Jpos")
  
  
  hof_table_Clean <- hof_table[-1,]
  hof_table_Clean
  
   
```

cleaning

```{r}
  hof_table_Clean <- hof_table_Clean %>%
  select(where(~ !all(is.na(.))))

 
```

Shaping

```{r}
  library(Lahman)
  head(HallOfFame, 3)
  
  # HallOfFame
  
  bbwaa <- hof_table_Clean %>% mutate(
    yearID = 2024,
    votedBy = "BBWAA",
    ballots = 385,
    needed = 289,
    inducted = ifelse(Votes>=289, "Y", "N"),
    category = NA,
    needed_note = NA) %>% 
    rename(votes = Votes) %>% 
    select(-`%vote`, -`Yrs`)
  
  
  
  bbwaa <- bbwaa %>%
    select("Name","yearID","votedBy","ballots","needed","votes","inducted","category","needed_note")
  
  #getting rid of the X- infront of some of the players names
  bbwaa$Name <- gsub("^X-", "", bbwaa$Name)

  
  print(bbwaa)
  
```

Names to player ID

```{r}
  bbwaa <- bbwaa %>%
    separate("Name", 
           into = c("first_name","last_name"), 
           sep = " ", 
           extra = "merge", 
           fill = "right")

  bbwaa <- bbwaa %>%
    mutate(
      playerID_base = str_c(last_name, str_sub(first_name, 1, 2)),
      count = ave(seq_along(playerID_base), playerID_base, FUN = seq_along),
      playerID = paste0(playerID_base, sprintf("%02d", count))
    ) %>%
    select(-count,-playerID_base,-first_name, -last_name) %>%
    select(playerID, everything()) 

  bbwaa
  
  #To lower case
  bbwaa$playerID <- tolower(bbwaa$playerID)
  #convert votes to numeric double
  bbwaa$votes <- as.numeric(bbwaa$votes)
  
  
  print(bbwaa)
```

Clean both datasets

```{r}
  bbwaa$playerID <- str_trim(bbwaa$playerID)
  HallOfFame$playerID<-str_trim(HallOfFame$playerID)

```

#### Connecting the two datasets

Merge with original HOF

```{r}
# HallOfFame
combined_data <- bind_rows(HallOfFame, bbwaa)

print(combined_data)

```
```{r}
  #old version
  HallOfFame %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2022))
  
  #new version
  combined_data %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2024))

```
Just the year 2024

```{r}
  combined_data %>% 
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(2015, 2025))
```

write to excel

```{r}
write.csv(combined_data, file="HallOfFame.csv", row.names = FALSE)
```
